### ISSUE TITLE
Different InstallESD.dmg Hashes on Macbook Pro 5,5

### ISSUE THREAD

**Issue by x44x45x41x4E** [drduh/OS-X-Security-and-Privacy-Guide#100]
Hi!

A friend  wants me to reformat his old Macbook Pro since he's not knowledgeable about it so I downloaded an Installer of OS X El Capitan via the App Store. `codesign` outputs are correct but the hashes for InstallESD.dmg are different. `sw_vers` output build number is 15D21. Is this because that its an old model? Anyway, below are the hashes. If anyone has the time for this same model and build version, I hope you could take the time to check the hash values for me. Thanks!

```
Macbook Pro (13-inch, Mid 2009)

sw_vers output
--------------------------
ProductName:	Mac OS X
ProductVersion:	10.11.3
BuildVersion:	15D21

InstallESD Hashes
--------------------------

SHA-1: ca4fc8f99f5d17d8193108ba31027cf6fd360048
SHA-256: c3d8a41ea5e0f28a678ba2e2c81453bc17db3295a376289aea60fcd84fd63d05

```

**Comment by drduh** [comment]
Thanks for reporting this. I don't have access to a 2009 MacBook, but perhaps the file is different because it includes an entirely different set of hardware drivers. I'm inclined to say `codesign` output is trustworthy, but I'll keep this ticket open in case anyone can reproduce the issue.

**Comment by drduh** [comment]
I'm still trying to get my hands on this model of MacBook. Maybe you can try the 10.11.4 image now that it's out, and let me know if those hashes match? Thanks.

**Comment by x44x45x41x4E** [comment]
They match now. I wonder why the one for 10.11.3 didn't match.

**Comment by drduh** [comment]
Probably driver-related, then. I'll reopen and investigate if I can ever find this model of Mac.
