### ISSUE TITLE
What your encrypted data says about you

### ISSUE THREAD

**Issue by TraderStf** [drduh/OS-X-Security-and-Privacy-Guide#101]
https://nakedsecurity.sophos.com/2016/03/18/what-your-encrypted-data-says-about-you/

> Crunching through metadata to do with network connections is usually called traffic analysis, and you might be surprised how much it gives away, even when the traffic itself is strongly encrypted

Without mentioning crossing all freely available data sources: browser fingerprints, human language analysis (technician inclined, or literature, old, young, origin; think police profilers ), daily/weekly time habits, caught by new ads/trackers, server logs, payments...

**Comment by drduh** [comment]
That is an insightful article, but I think, again, is too general to be applicable for this Mac-specific guide.
