### ISSUE TITLE
Google Chrome extension secretly redirect users to ad pages

### ISSUE THREAD

**Issue by TraderStf** [drduh/OS-X-Security-and-Privacy-Guide#105]
https://nakedsecurity.sophos.com/2016/04/06/chrome-extension-was-secretly-redirecting-users-to-ad-pages/

> Reddit user Scarazer wrote that he’d found the same malicious code infecting a number of other Google Chrome extensions, including Chrome Currency Converter, Web Timer, User-Agent Switcher, Better History, 4chan Plus, and Hide My Adblocker.
As of Tuesday afternoon, the only extension in that list that had been removed from Google’s Chrome web store was 4chan Plus. Google also banned Better History after users encouraged each other to write reviews reporting it.

**Comment by drduh** [comment]
That's not totally unexpected. Users ought to exercise caution when installing software from the Internet, and this certainly includes browser extensions. I'll try to make this point clearer the next time I take a pass at updating the guide. Thanks for bringing this to attention.
