### ISSUE TITLE
Git in OS X puts developers at risk - 19 github projects for security pros

### ISSUE THREAD

**Issue by TraderStf** [drduh/OS-X-Security-and-Privacy-Guide#106]
http://www.csoonline.com/article/3058602/security/outdated-git-version-in-os-x-puts-developers-at-risk.html

Lot of resources, trying some for the moment.
http://www.csoonline.com/article/3058594/security/19-open-source-github-projects-for-security-pros.html

**Comment by drduh** [comment]
It would be useful to paraphrase the nature of the vulnerability and risk in the GitHub Issue, along with information regarding the versions of softwar affected, and whether a patch is available. The linked content looks to be behind a paywall, too.

**Comment by drduh** [comment]
There appears to be a fix for this in the latest version of Xcode 7.3.1: https://support.apple.com/en-us/HT206338
