### ISSUE TITLE
Temporary security advisory

### ISSUE THREAD

**Issue by vsaw** [drduh/OS-X-Security-and-Privacy-Guide#107]
The [issue about Git](https://github.com/drduh/OS-X-Security-and-Privacy-Guide/issues/106) makes me wonder how temporary security advice should be handled.

The git case is a perfect example where OS X users are at the moment at risk but in the future apple might fix it. Others is the Roaming feature of SSH. Users are only required to fix these until a patched version becomes available.

In my opinion the main README.md not the correct place to put all this temporary advice, but it is also to valuable to be lost. This brings me to the question where to put it?

One option would be actually to convert the Guide into a [GitHub Page](https://help.github.com/categories/github-pages-basics/) and have subsections for temporary advice.

**Comment by TraderStf** [comment]
I think it would be nice to have 3 documents.
- Ressources, where we add tools
- How-to, very detailed explanations for very specific issues
- Alerts, latest one or old-one not-yet solved, eg. old-sparkles still in dozen of apps

Only the author add one of this type, no one else come to comment.
Some kind of directories, lists.
Comments and discussion would required to open a new thread.

**Comment by drduh** [comment]
Maintaining such an advisory list sounds like a thankless, dull task. I'll leave it to readers of this guide to raise GitHub Issues when a security advisory is worth mentioning and discussing, if they wish. The Issue can be kept open until it is patched and resolved. Really, the user is ultimately responsible for staying informed on the latest security news, however.
