### ISSUE TITLE
how to generate passwords securely conforming to required character sets

### ISSUE THREAD

**Issue by 9Yg1rxeSeha90ZU1** [drduh/OS-X-Security-and-Privacy-Guide#111]
https://github.com/drduh/OS-X-Security-and-Privacy-Guide/blob/master/README.md#passwords

Here is a generic way that lets the user also control the character set, length, and number of passwords.

```LANG=C tr -dc 'a-zA-Z0-9' < /dev/urandom | fold -w 16 | head -n 1```

Where the argument to tr is the character set required for your password, argument to fold is the password length, and the argument to head is the number of passwords to generate.

**Comment by quinncomendant** [comment]
On OS X 10.11.5:

    [q@localhost] LANG=C tr -dc 'a-zA-Z0-9' < /dev/urandom | fold -w 16 | head -n 1
    tr: Illegal byte sequence

Setting `LC_ALL=C` solves this:

    [q@localhost] LC_ALL=C tr -dc 'a-zA-Z0-9' < /dev/urandom | fold -w 16 | head -n 1
    6dzbiTYjU8HeWQ6P
