### ISSUE TITLE
a potential alternative to dnscrypt -- dnsmasq + Tor DNS

### ISSUE THREAD

**Issue by 9Yg1rxeSeha90ZU1** [drduh/OS-X-Security-and-Privacy-Guide#112]
https://github.com/drduh/OS-X-Security-and-Privacy-Guide/blob/master/README.md#dnsmasq

Instead of utilizing dnscrypt, which can be hard to depend upon due to the limited number of servers and the fact that a hostile network could easily block the list of servers, consider utilizing Tor DNS in the dnsmasq config as the upstream server. The first lookup will be relatively slow, but cached for future lookups (until TTL expiration).

```
server=127.0.0.1#9053
```

**Comment by drduh** [comment]
How do you run Tor to utilize that port? I've tried both Tor Browser and Tor from Homebrew - neither listened on port 9053. Feel free to PR your recommendation.

**Comment by 9Yg1rxeSeha90ZU1** [comment]
DNSPort is the torrc config option if you don't want dnsmasq. You can set it to 53, but you would need to run as root (not recommended), or authorize the low port using something like setcap equivalent on osx.

However, you can also specify dnsmasq to forward the query from dnsmasq port 53 to 127.0.0.1:9053, where tor is listening.

**Comment by 9Yg1rxeSeha90ZU1** [comment]
there is also HTTPS DNS, which is new from Google. I implemented a client but it is not ready for release yet. This would encrypt all DNS queries over HTTPS with TLS.

https://developers.google.com/speed/public-dns/docs/dns-over-https

**Comment by drduh** [comment]
Yes, I understand the DNSPort directive, but my question is how are you running Tor to use that configuration? Through Tor Browser, Homebrew Tor, built from source, or some other way?

**Comment by 9Yg1rxeSeha90ZU1** [comment]
Both homebrew tor and tor source work fine, yeah. It's a UDP port. You may have only looked at TCP? Just do you know though, tor only supports a limited number of DNS record types. It doesn't support PTR, MX, etc. So just be aware of that until I release my Google HTTPS DNS protector...

**Comment by drduh** [comment]
Giving this more thought, I think the use case is too esoteric for most folks; routing DNS over the Tor network is more a more specialized recommendation which I don't think will appeal to *most* readers. If you feel really compelled, please send a PR with detailed instructions for setting it up, otherwise I'll close this ticket since I don't plan on making this change myself.
