### ISSUE TITLE
How to permanently override configurable hostname parameters

### ISSUE THREAD

**Issue by 9Yg1rxeSeha90ZU1** [drduh/OS-X-Security-and-Privacy-Guide#115]
Here are some steps to override the configured hostname parameters permanently:

```
$ sudo sysctl kern.hostname=localhost
$ sudo hostname -s localhost
$ sudo scutil --set HostName localhost
$ sudo scutil --set LocalHostName localhost
$ sudo scutil --set ComputerName localhost
```

Add this line to /etc/sysctl.conf:
kern.hostname=localhost

**Comment by drduh** [comment]
This has been working well for me for a while now. I'll add it to the guide soon, or you can send a pull request if you wish to do it.

**Comment by BobsUncle** [comment]
what's the benefit of changing the hostname?

**Comment by drduh** [comment]
The hostname may be advertised to the local network by sharing services. So if your MacBook is called 'Bob's Uncle MacBook', everyone on the network will know it's your laptop.
