### ISSUE TITLE
transparent proxying of all outgoing tcp traffic to tor

### ISSUE THREAD

**Issue by 9Yg1rxeSeha90ZU1** [drduh/OS-X-Security-and-Privacy-Guide#116]
Section: https://github.com/drduh/OS-X-Security-and-Privacy-Guide/blob/master/README.md#tor

It is useful to transparently redirect all traffic to tor. However, this is exceedingly difficult on later versions of OS X, especially because ipfw is removed and pf does not work the same as it does on vanilla BSD. The "rdr" redirect directive does not support outgoing connections (only inbound), but more frustrating is the fact that attempting to workaround this restriction is not working on El Capitan via the "route-to" directive. A good discussion of this is below.

https://serverfault.com/questions/709369/pf-mac-os-x-rule-to-redirect-all-traffic-to-a-specific-ip-port

Note that there is no simple OS X solution at this time, at least to this user. Even the folks at Tor Project don't seem to list a free solution either. There is a vanilla BSD recipe, but that also does not work on El Capitan :( And many of the vanilla BSD pf parameters like "user" do not exist on El Capitan.

https://trac.torproject.org/projects/tor/wiki/doc/TransparentProxy#BSDPF

A non-free solution is to utilize the Proxifier app, which is a closed source product, but according to VirusTotal, is not flagged as malicious. The solution utilizes a custom kernel module to handle the redirections.

https://www.proxifier.com/

This app is also available as a cask in brew, but I would NOT utilize it since there is NO HASH CHECK on the binary. However, once you get the app up and running, it is fairly straight forward to configure transparent proxying via tor. Ideally, it would be great if someone identified and posted here a completely free and working solution that is open source or utilizes some OS X pf tricks to workaround the quirks mentioned above.

**Comment by 9Yg1rxeSeha90ZU1** [comment]
Actually, just found a few 0days in Proxifier. Not good after all... *sigh*

**Comment by drduh** [comment]
Hello and thanks for opening the recent issues with your suggestions. I agree with most of them - and feel free to PR the proposed changes, or I will implement them myself - however, I must dissent on this one. It does not seem like a good idea to route all Mac traffic through Tor, at least not for a typical user. The reason being, is that many applications may inadvertently establish network connections which may reveal some personally identifiable information about the user.

One immediate example which comes to mind is the About This Mac dialog, which apparently sends some information [in plaintext](https://github.com/fix-macosx/yosemite-phone-home/blob/master/eff-user-r0/Applications/Utilities/System%20Information.app/Contents/MacOS/System%20Information/20141019T192957Z-effuser-%5B172.16.174.146%5D:49495-%5B23.3.12.195%5D:80.log). So my concern is with accidentally exposing network traffic to a Tor exit node, which may compromise anonymity and harm privacy in this subtle way.

Or say the Mail application tries to establish a connection to Gmail, for example, over the Tor network, triggering potentially confusing Google account alerts or even some unexpected account lockdown (just a hypothesis, though).

As you've pointed out, it's also not a trivial matter to force *all* traffic to route through a proxy, and perhaps for good reason. A more sure solution would be to configure Tor and the firewall on a router the Mac connects through, but again, caution is advised in doing so. Even better still would perhaps be specialized instructions for configuring a specific application to route over Tor (SSH, for example).

**Comment by 9Yg1rxeSeha90ZU1** [comment]
I agree. I think the emphasis should be on avoiding web tracking and not necessarily obtaining privacy. Those who really care about not leaking anything at all should probably be using Subgraph OS or Tails :) per your comment though regarding malicious exit nodes, then I guess you could configure Tor to only route HTTPS and other secure protocols via tor so that risk is mitigated and one still gains some web tracking protections. But feel free to add this to the list any way you choose and then close it out. Cheers! :)
