### ISSUE TITLE
Proposal for a "Linux Security and Privacy Guide"

### ISSUE THREAD

**Issue by 9Yg1rxeSeha90ZU1** [drduh/OS-X-Security-and-Privacy-Guide#122]
Is there an existing "Linux Security and Privacy Guide" already developed? If not, I have been hardening my own Linux systems for a long time and could share my own tips. Let me know if this already exists or not in a similar format to the OS X version here. A lot of the old original guides are extremely outdated due to the fact that so much has changed in Linux / distributions over the years. A good example of this is when Ubuntu added commercial Amazon integration and spying on all Ubuntu users a few years ago. Let me know your thoughts :)

**Comment by vonrac** [comment]
I don't want to comment with just a 👍, but yeah, let's do that. I'll happily contribute to a Linux SPG. Given the breadth and complexity of all the Linux distros, it might make sense to start with only a few ones. Perhaps the most popular, including Ubuntu (I use Trisquel).

**Comment by drduh** [comment]
I'm aware of at least this guide - https://github.com/lfit/itpol/blob/master/linux-workstation-security.md - targeted to Linux workstation users. It looks very comprehensive and is almost as popular as this repository. Perhaps that existing resource could stand to benefit from your contributions; a similar SPG for Linux is a worthwhile pursuit.

**Comment by TraderStf** [comment]
https://www.inversoft.com/guides/2016-guide-to-user-data-security
https://github.com/inversoft/2016-security-scripts

**Comment by Atavic** [comment]
https://github.com/ernw/hardening
