### ISSUE TITLE
using dnscrypt a long time - now it wouldn't work

### ISSUE THREAD

**Issue by badummtss** [drduh/OS-X-Security-and-Privacy-Guide#123]
Need help with dnscrypt-proxy, i still have dnsmasq running (checked with dig and the ad flag is set).
Now when i switch to my DnsCrypted Network in Menu->enviroment (or places? don't know the english name for this because my OS ist in German and the word is "Umgebung"), no internet connection.

What can i do????

**Comment by TraderStf** [comment]
This will perhaps help... but it has been a long time.
I think there is a bug in OSX - Syst Pref - Network, sometimes it does not detect changes.
Create a new setting DHCP,DNS... and/or uninstall DNSCrypt.
In DNSCrypt you can also define several things manually, not using the menu.
Sorry for not being clearer.
If it does help, check my previous (closed) post, I have report similar errors but impossible to reproduce all the time.

**Comment by badummtss** [comment]
i checked all of your steps. The thing about the Network Settings in OSx...  i think is the Devil...
I will install the last Combo Update this weekend over my installation, and when finished i hope i get my settings back.
I use a tool to change my settings automatically (ControlPlane), Littlesnitch is switching the Network Locations....
aaaaaw i don't understand what the problem is (e.g. in the plist file i have used very much different commands: --ephemeral-key --provider-key +name etc...) nothing will work.
The only way to come out from any blocking things is this tool, for surfing is tor okay, but when much sites are blocked due to content filtering from my isp... not a good business...

**Comment by rprimus** [comment]
On Tue, Jun 14, 2016 at 10:09:36AM -0700, badummtss wrote:
> i checked all of your steps. The thing about the Network Settings in OSx...  i think is the Devil...
> I will install the last Combo Update this weekend over my installation, and when finished i hope i get my settings back.
> I use a tool to change my settings automatically (ControlPlane), Littlesnitch is switching the Network Locations....
> aaaaaw i don't understand what the problem is (e.g. in the plist file i have used very much different commands: --ephemeral-key --provider-key +name etc...) nothing will work.
> The only way to come out from any blocking things is this tool, for surfing is tor okay, but when much sites are blocked due to content filtering from my isp... not a good business...

Tue 14 Jun 2016 19:37:27 BST

It stopped working for me this morning at 05:50 BST.

In the plist, ```dnscrypt.eu-dk``` was the
provider.

I changed this to ```dnscrypt.eu-nl```, unloaded
and loaded and all was well.

I had noticed that web pages were progressively
loading more slowly throughout the morning until
the total stop.

HTH.

-- 
-primus (Train yourself and be your own master.)
"First solve the problem, then code!"
Narrowness of experience leads to narrowness of imagination.
http://www.catb.org/esr/faqs/smart-questions.html
http://www.chiark.greenend.org.uk/~sgtatham/bugs.html

GPG Key: DB3FB476
Key fingerprint: B0FB C67E 2E7E 7032 7FE6  7FBC 28E9 2848 DB3F B476

**Comment by badummtss** [comment]
ok i have changed it like rprimus wrote. it is exactly this problem...
dude you made my day - high five ;)
