### ISSUE TITLE
Alternative shasum 0e063fd87d5b0a4f68dbd35da95b2018748f88eb for InstallESD.dmg for OS X 10.10.5

### ISSUE THREAD

**Issue by grahamperrin** [drduh/OS-X-Security-and-Privacy-Guide#125]
Downloaded with the App Store yesterday (2016-06-17), the result and a discrepancy was noted at http://apple.stackexchange.com/a/246331/8546

Today I trashed that copy, emptied the trash, restarted the Mac, gained a fresh copy and obtained the same result from shasum: 

```
sh-3.2$ date ; uptime ; cd /Applications/Install\ OS\ X\ Yosemite.app/Contents/SharedSupport/
Mon 18 Jul 2016 18:53:47 BST
18:53  up 58 mins, 2 users, load averages: 2.81 3.78 3.65
sh-3.2$ shasum InstallESD.dmg ; sw_vers
0e063fd87d5b0a4f68dbd35da95b2018748f88eb  InstallESD.dmg
ProductName:	Mac OS X
ProductVersion:	10.12
BuildVersion:	16A239m
sh-3.2$ 
```

# The discrepancy

0e063fd87d5b0a4f68dbd35da95b2018748f88eb for downloads today and yesterday differs from 
ef5cc8851b893dbe4bc9a5cf5c648c10450af6bc at https://github.com/drduh/OS-X-Security-and-Privacy-Guide/blob/master/InstallESD_Hashes.csv

**Comment by grahamperrin** [comment]
The first response to http://forums.macrumors.com/posts/23136438 also shows (in a screen shot) 
0e063fd87d5b0a4f68dbd35da95b2018748f88eb 

Without performing an installation from what I downloaded, my first guess is that Apple has distributed an updated installer for an operating system with an unchanged build reference.

**Comment by 9Yg1rxeSeha90ZU1** [comment]
Is it not true that mounting a DMG file often changes the hash?

**Comment by drduh** [comment]
DMG files don't change when mounted. You're getting a different hash because 10.11.6 was released today. Feel free to PR InstallESD_Hashes.csv with the new values.

**Comment by grahamperrin** [comment]
> 10.11.6

That's El Capitan. 

This issue is for the values for 10.10.5 Yosemite. If there's to be a PR then it may be useful to know the version and build of the .app that contained the earlier .dmg
 relate

**Comment by 9Yg1rxeSeha90ZU1** [comment]
Actually, @drduh, it is quite often the case that DMG files ARE MODIFIED when mounted! Don't believe me? Try it yourself...

$ wget -q 'https://dist.subgraph.com/downloads/Vega64.dmg'
$ md5 Vega64.dmg 
MD5 (Vega64.dmg) = b828ad1d67e522cfc0faf9ba7daca009
$ hdiutil attach Vega64.dmg 
/dev/disk2          	                               	/Volumes/Vega
$ md5 Vega64.dmg 
MD5 (Vega64.dmg) = e37b2ac0aecbbe0bf024ea4594ebe920

Q.E.D.

**Comment by TraderStf** [comment]
I was not sure but @9Yg1rxeSeha90ZU1 comments confirm my idea.
Some DMGs must be burn on CD/DVD before mounting it or they/their content will not work, I think it was for some apple stuff, long time ago...

**Comment by drduh** [comment]
@grahamperrin My apologies, I had misread your bug title. [Security Update 2016-004](https://support.apple.com/en-us/HT206903) is probably what's causing the discrepancy. I would be surprised if the build version isn't updated, however. Can you install and check, please?

It appears you're correct, @9Yg1rxeSeha90ZU1:

```
$ xxd Vega64.dmg > before
$ hdiutil mount Vega64.dmg >/dev/null
$ xxd Vega64.dmg > after
$ diff before after
69c69
< 0000440: 0000 01cb 0000 1812 0000 0000 0000 0001  ................
---
> 0000440: 0000 01cb 0000 1813 0000 0000 0000 0001  ................
```

However, that file is read/write image, unlike InstallESD.dmg, which is UDIF read-only (you can check with `hdiutil info` or `hdiutil imageinfo`), so that's unlikely the cause here.

**Comment by drduh** [comment]
I'm also getting `0e063fd87d5b0a4f68dbd35da95b2018748f88eb` / `6a2d563b89d4c2733e8ff087c16db0caaa6594375ac835b3110df4306edb2459` for the latest 10.10.5 InstallESD.dmg.

Interestingly enough, each file on the mounted volume is identical, though. 

```
$ diff <(find /Volumes/OS\ X\ Install\ ESD/ -type f -exec shasum -a 256 {} \+ | sed 's%/Volumes/.*/%%') <(find /Volumes/OS\ X\ Install\ ESD\ 1 -type f -exec shasum -a 256 {} \+ | sed 's%/Volumes/.*/%%') ; echo $?
0
```

More random poking about:

```
$ stat -f %z *dmg
5718943631
5718940459
```

```
$ hdiutil info | grep block
blockcount      : 11760932
blocksize       : 512
blockcount      : 11760932
blocksize       : 512
```

```
$ diff <(tail -c 512 InstallESD-latest.dmg | hexdump -C) <(tail -c 512 InstallESD-current.dmg | hexdump -C)
2c2
< 00000010  00 00 00 00 00 00 00 00  00 00 00 00 00 59 71 97  |.............Yq.|
---
> 00000010  00 00 00 00 00 00 00 00  00 00 00 00 00 59 71 9e  |.............Yq.|
9c9
< 000000d0  00 00 00 00 00 00 00 00  00 00 00 01 54 d7 ef 46  |............T..F|
---
> 000000d0  00 00 00 00 00 00 00 00  00 00 00 01 54 d7 ef 4d  |............T..M|
```

Here is a mysterious Pastebin from February with MD5 sums of both DMGs: http://pastebin.com/CDrPPjsj

I can't explain the discrepancy at this time.

**Comment by 3ji7ja0jb9c** [comment]
[I suggest we checksum partition/slice, instead of or in addition to InstallESD.dmg container.](http://macintoshgarden.org/apps/mac-os-x-intel-microprocessor)
