### ISSUE TITLE
Little Flocker is now Beta

### ISSUE THREAD

**Issue by ghost** [drduh/OS-X-Security-and-Privacy-Guide#132]
Hey @drduh just wanted to drop a line and let you know LF is at beta 2 now, looking pretty good, lots of good user feedback to help fix bugs. Not much new to put into beta 3 yet, which is a good sign.

**Comment by drduh** [comment]
Thanks a lot. I have some ideas in mind about re-arranging the guide in a way to showcase the various available Mac security software, maybe with a feature comparison matrix, or the like. I'll be sure to take a look at LF soon and include it more formally.

**Comment by andresgottlieb** [comment]
Just to let you know that the Little Flocker link is dead. It looks like the owner [moved from github to gitlab](https://twitter.com/JZdziarski/status/778949510437359617) and [decided to close the source and charge for the software](http://www.littleflocker.com/)

**Comment by miccal** [comment]
Hello @drduh, Little Flocker is now out out of beta, and is now at version [1.0.0.](https://www.littleflocker.com/download/).
