### ISSUE TITLE
Hosts file with 0 or 127?

### ISSUE THREAD

**Issue by TraderStf** [drduh/OS-X-Security-and-Privacy-Guide#133]
Hello,

I have red different comments... which one is correct or better on macOS?
As it's not the same on other OS, another mess... 🙄

Sorry if I'm not very precise, I can search them back if you really need it. 

0 adds overhead on the local network, use 127.0.0.1
127.0.0.1 requires one more 'redirect', use 0...

Can this be solved/enhanced by adding other declarations in the hosts file?
<pre>127.0.0.1       localhost
255.255.255.255	broadcasthost
::1             localhost
# fe80::1%lo0   localhost
# 0             localhost.localdomain
# 0             local
</pre>

Are the last 3 lines required, it's not in macOS default file?

Are 0 and 0.0.0.0 totally equal?

What's the maximum of characters for several domains on a single line?
0 example.com example.fr example.de

Thanks

_[iHosts](https://itunes.apple.com/us/app/ihosts/id1102004240?mt=12) is an alternative to gasmask, though can't handle huge files, use BBEdit or TextWrangler._

**Comment by alsk23** [comment]
Ok, this may not help a lot, but:

```

**Comment by baitnfatty** [comment]
TraderStf,

When you see a # at the front of the line, it is a comment, and there for is not read. you can delete the last three lines if you would like, although there is not difference, as they are just there to show you other possibilities. 

Please read: https://www.freebsd.org/doc/handbook/configtuning-configfiles.html

It is a configuration page for FreeBSD which is the base of OS X. Alternatively if you are good with terminal just type "man hosts" and it will give you the same info.

The only thing that matters is that the IP must be first when adding things, their domain and alias do not matter, although if you are adding many alias' then you may want to put them last which is the typical configuration. 

Also, You can delete just about everything in the file, but leave the ::1 and 127.0.0.1 localhost designations or your computer will not know how to communicate with itself, which is an essential thing for it to be able to do. 

Have a good day.

**Comment by drduh** [comment]
Thanks to @baitnfatty I think this is well answered!

**Comment by TraderStf** [comment]
@baitnfatty, I did not noticed your answer. thank you very much.

Sorry for my bad English.
I know the # comment, I was trying to ask if the IP6 formats, line 3+4, were useful if IP6 is activated on the computer.

Also trying to get a confirmation/comments, from the big guys here, about either to use 0 or 127.0.0.1, did quite a lot of research but did not found any explanations in official/original docs.

I close this thread, don't want to bother our boss ;-)
