### ISSUE TITLE
Mention how to seed PRNG before activating Filevault

### ISSUE THREAD

**Issue by felixgr** [drduh/OS-X-Security-and-Privacy-Guide#140]
For example:

    cat > /dev/random
    [type random letters for a while and press ctrl-c]

**Comment by MikeyJck** [comment]
This is not required. 

1. Please [do not](https://sockpuppet.org/blog/2014/02/25/safely-generate-random-numbers/) use `/dev/random`, use `/dev/urandom`.
2. `/dev/urandom` [reseeds](http://www.2uo.de/myths-about-urandom/#re-seed) itself already. 

Also, see this [excellent talk](https://media.ccc.de/v/32c3-7441-the_plain_simple_reality_of_entropy) by @FiloSottile on entropy and `/dev/urandom`

**Comment by dnwe** [comment]
@mikeyjck this is OS X, not Linux. Check man random (as per the guide). The /dev/urandom on OS X is just a nod to Linux, it's not the same impl. Both /dev/ randoms are non-blocking and reseeded automatically (as this guide already describes), but (theoretically) there's no guarantee at first boot that enough will have been generated to make a good encryption in FileVault. 

I think this issue was asking for elaboration on how you might seed additional entropy at first boot before enabling FileVault (which the guide already suggests you might like to do)

**Comment by MikeyJck** [comment]
@dnwe You are correct apologies for my mistake.

**Comment by asvc** [comment]
@dnwe , Imagining FileVault was enabled pretty much right after OSX installation; what practical implications would it have to the encryption?

**Comment by dnwe** [comment]
@asvc I'm merely quoting what already exists in the guide at https://github.com/drduh/OS-X-Security-and-Privacy-Guide/blob/master/README.md#full-disk-encryption where @drduh recommends waiting some time after boot before enabling FileVault.

**Comment by asvc** [comment]
ping @drduh

**Comment by FiloSottile** [comment]
I'd be very surprised if the OS X /dev/[u]random was low-entropy at
boot, but if that's the case, it should be a talk at DEF CON, not a
recommendation on a guide.

**Comment by dnwe** [comment]
@FiloSottile again I believe it's specifically first boot after a new OS install. A cache of entropy is stored and restored to disk by the SecurityServer and can be used on subsequent boots. 

https://developer.apple.com/legacy/library/documentation/Darwin/Reference/ManPages/man4/random.4.html

**Comment by felixgr** [comment]
In this issue I'm asking for a more practical advice for users that want to additionally seed the Yarrow PRNG by writing to /dev/random before activating FileVault. FileVault keys are generated from the PRNG and my estimate is that the entropy that went into the PRNG before that is rather low. We did experiments with 1000 fresh install boots and the estimated effective fresh reboot seed entropy is **around 320 bits**:

    prngInitialize()
    prngInput(inbuflen = 8)		source: microtime()
    prngForceReseed(ticks = 50)	recalculate pool
    prngInput(inbuflen = 20)		source: /var/db/SystemEntropyCache (updated every 6h)
    prngForceReseed(ticks = 50)
    prngInput(inbuflen = 256)	source: mach_absolute_time() (41 * sizeof(mach_timespec_t)) via kdbg_getentropy(), collectEntropy(), and also 1 * current time
    prngInput(inbuflen = 72)
    prngForceReseed(ticks = 50)

From those seeds, microtime and current time are predictable. SystemEntropyCache is empty.
7 of 8 bytes of mach_timespec_t is also predictable.

In most systems, SystemEntropyCache from the first boot saves the day so we didn't go to DEFCON :) but it's still pretty low.

See https://eprint.iacr.org/2012/374.pdf for more info. This is based on 10.7.

**Comment by asvc** [comment]
@felixgr , would it be beneficial to disable and enable FileVault in that case? This should lead to the disk being re-encrypted with the new key.

**Comment by felixgr** [comment]
@asvc well, that requires two reboots so entropy would increase. But it's not really practical. I recommend to write to `/dev/random`.

**Comment by asvc** [comment]
@felixgr , I've meant situation if the HD was encrypted after the 1st boot.
