### ISSUE TITLE
Add recommendations around VMs

### ISSUE THREAD

**Issue by felixgr** [drduh/OS-X-Security-and-Privacy-Guide#142]
For some users with more powerful devices it makes sense to run most of their day-to-day work in a VM. Some of the guide would apply to the secure host OS but some other parts (like homebrew and Browser) would be better for a VM. If you add a section on VMs, also maybe add how to configure e.g. VMWare to have proper guest isolation and how to use the restore to get back to a 'known' good state.

**Comment by drduh** [comment]
I got it started, but there is a lot more to say on the subject, so don't be shy with pull requests.
