### ISSUE TITLE
Homebrew and /usr/local

### ISSUE THREAD

**Issue by Eitot** [drduh/OS-X-Security-and-Privacy-Guide#145]
It has always bugged me that Homebrew installs itself into `/usr/local` and claims ownership over it instead of root:wheel. For the longest time, Homebrew’s git repository was installed directly in that path (nowadays in `/usr/local/Homebrew`). Nevertheless, Homebrew still insists on changing the ownership of `/usr/local/bin` and `/usr/local/lib`, which means that the installing user can install any binaries or libraries without additional privileges.
```bash
==> The following existing directories will be made group writable:
/usr/local/bin
/usr/local/include
/usr/local/lib
/usr/local/lib/pkgconfig
==> The following existing directories will have their owner set to my_admin_account:
/usr/local/bin
/usr/local/include
/usr/local/lib
/usr/local/lib/pkgconfig
==> The following existing directories will have their group set to admin:
/usr/local/bin
/usr/local/include
/usr/local/lib
/usr/local/lib/pkgconfig
```

Since `/usr/local/bin` takes precedence over `/usr/bin` and `/bin` (in `/etc/paths`), any malicious program could simply put binaries or libraries there and effectively ‘overwrite’ the ones installed in other system paths.
```bash
$ cat /etc/paths
/usr/local/bin
/usr/bin
/bin
/usr/sbin
/sbin
```

I am of the opinion that this is a bad practice and it should be mentioned explicitly. I personally have installed Homebrew in `~/.homebrew`, despite their advice against it. I have not come across any problems so far.

**Comment by hidisem627** [comment]
How do you install binary files that are already provided by MacOS (e.g. `git` or `ruby`) if homebrew does not take precedence over `/usr/bin` and `/bin`?

**Comment by hazcod** [comment]
@hidi: export PATH=“/usr/local/bin:$PATH”

**Comment by hidisem627** [comment]
You recommend giving homebrew priority over `/usr/bin` and `/bin`. But that's exactly what this guide is supposed to prevent. So this cannot be a solution.
