### ISSUE TITLE
Firmware password

### ISSUE THREAD

**Issue by gdbinit** [drduh/OS-X-Security-and-Privacy-Guide#25]
Regarding the firmware password.
It is possible (and rather easy) to remove it with physical access to the machine via a SPI flasher.
It is good enough against lame thieves that have no info on how to do this but there are specialised flashers for this purpose being sold on the Internet so it's a protection on a limited threat scenario. Still it is recommended to have one anyway.

Best,
fG!

**Comment by drduh** [comment]
Hey Pedro,

I added a small footnote in https://github.com/drduh/OS-X-Yosemite-Security-and-Privacy-Guide/commit/b039a0df3da1175a2bc1f75448423bb4563cc61b after seeing your [tweet](https://twitter.com/osxreverser/status/638465623450873856).

Maybe you would like to send a pull request to add more firmware information? I think everyone will benefit a lot from your expertise. Else, I'm happy to mention physical access & SPI flasher as possible, though unlikely, attacks against the firmware password.

Thanks

**Comment by gdbinit** [comment]
Yeap, let met try to write something about that part and make a pull request. :-)

**Comment by TraderStf** [comment]
Perhaps should mention that with a firmware pw, you can no more use safe start (and perhaps other options).

**Comment by christopheranderton** [comment]
Firmware passwords is in some cases fairly easy to remove (if you have physical access to the machine as stated by @gdbinit ). Specially on ”older” MacBook Pros (example 2009 models). Had my MacBook Pro 15" (MacBookPro5,3) stolen, and when it was recovered after a month by the Police, the thieves had set a Firmware password. At the time, you removed one RAM module, resetted the PRAM x3 if remember it correctly. 

No need to have a flasher. Can do a short write up about this (and what models, method and Firmware versions and so on).

**Comment by drduh** [comment]
My firmware flashing knowledge is limited; I welcome your pull requests.

**Comment by drduh** [comment]
Please go ahead and send me a PR when you're ready to suggest Firmware section changes. Pedro, I will be especially grateful if you could contribute some of your wisdom to the guide.
