### ISSUE TITLE
El Capitan OpenSSL

### ISSUE THREAD

**Issue by mikemcquaid** [drduh/OS-X-Security-and-Privacy-Guide#39]
In El Capitan OpenSSL's libraries are still provided but headers have been removed from the OS X SDKs. As a result, you should no longer encourage the use of `brew link openssl --force` as `clang`'s default link and library paths mean that you may end up using newer Homebrew OpenSSL headers but link against the older, system version.

For a reproduction example see https://gist.github.com/tdsmith/4b502c5cc6e7d358acdf

**Comment by drduh** [comment]
Thanks for the heads up, @mikemcquaid. I will mention it in the El Cap guide which I'll write when the OS is released.

**Comment by mixania** [comment]
Hey @drduh , not related to this issue but how compatible is this guide with El Capitan in general? Wish I've seen this repo when I was on Yosemite :(

**Comment by nickpellant** [comment]
@mixania I've gone through this guide on El Capitan without any hitches.

**Comment by poulagah** [comment]
any revision for el capitan is planned ?

**Comment by mixania** [comment]
@nickpellant thanks, nice to know

**Comment by TraderStf** [comment]
http://www.techrepublic.com/resource-library/whitepapers/eliminate-blind-spots-in-ssl-encrypted-traffic
http://www.thoughtcrime.org/software/sslstrip/

**Comment by drduh** [comment]
Hey @poulagah I am planning to clone this into an updated El Cap guide in the next week or so. Stay tuned!

**Comment by poulagah** [comment]
@drduh yeah you rocks !

**Comment by SKGrimes** [comment]
@drduh there were some issues with the SIP on el Cap, and also unloading some services causes CPU spikes. Not sure when you plan on releasing the guide, and I didn't want to open a seperate issue, but if you would consider starting a new repo with release info that would be awesome. Great guide BTW. Cheers.

**Comment by drduh** [comment]
Thanks for letting me know, @SKGrimes. I will try and get a preliminary El Cap guide by the end of the week, time permitting.

**Comment by MatthewHerbst** [comment]
Is this still accurate for Sierra?

**Comment by MatthewHerbst** [comment]
FYI, ondoing `brew install --force openssl` Homebrew outputs:

```
...
Generally there are no consequences of this for you. If you build your
own software and it requires this formula, you'll need to add to your
build variables:

    LDFLAGS:  -L/usr/local/opt/openssl/lib
    CPPFLAGS: -I/usr/local/opt/openssl/include
...

So maybe that solves this issue for Sierra as well?
