### ISSUE TITLE
Useless and/or holes in protections

### ISSUE THREAD

**Issue by TraderStf** [drduh/OS-X-Security-and-Privacy-Guide#41]
May I suggest a section, of few additions to mention useless/weak and/or holes in protections/tools/settings and if the available alternatives.
Sorry no time to do it.
Thanks for your great work.

VPN - PPTP, useless unsecure, better than nothing
VPN but still use ISP DNS, not all exchange through VPN and VPN with DNSLeak-browser involved
VPN disconnect without killswitch (block all communication if vpn stops)
VPN and accessing your usual accounts, eg gmail, webmail, contacts...
WIFI - WEP
Mobile phone/Computer with Location activated
Browser Finger Print, uses one only for secure works, another for whatever
HTTP with MiTM, move to HTTPS

You get the idea...
Forgot this one, still used by so many, not by the audience here of coz :-) Zip passwords !

**Comment by berndogg420** [comment]
who are you i do not understand your message

**Comment by TraderStf** [comment]
@berndogg420 who cares anyway 🎪

**Comment by jzorn** [comment]
I think, @TraderStf suggested to add more information on weak protocols such as PPTP and WEP and a note to avoid these.

**Comment by TraderStf** [comment]
@jzorn, exactly thank you for decrypting my BASE64(VGFyemFuIEVuZ2xpc2g=)

**Comment by berndogg420** [comment]
I LOVE this SLOTS game that I’ve been playing lately! The payouts are great
and I’m having so much fun with it! I thought you might want to check it
out too!
You’ll get Get over 1 MILLION FREE coins to play with if you install today!
I hope we can play it together soon!
You can Download it here for free: slots-favorites.superluckycasino.com
