### ISSUE TITLE
For El Capitan

### ISSUE THREAD

**Issue by TraderStf** [drduh/OS-X-Security-and-Privacy-Guide#50]
Open this thread to add resources and info about El Capitan.
Some might be obsolete.

https://en.wikipedia.org/wiki/Sparse_image

http://osxdaily.com/2015/09/29/prepare-mac-os-x-el-capitan/
http://osxdaily.com/2015/09/30/create-os-x-el-capitan-boot-install-drive/
http://osxdaily.com/2015/10/01/clean-install-os-x-el-capitan-mac/
http://osxdaily.com/2015/10/09/howto-downgrade-os-x-el-capitan-mac/

http://osxdaily.com/2015/10/05/disable-rootless-system-integrity-protection-mac-os-x/
http://osxdaily.com/2015/05/04/disable-gatekeeper-command-line-mac-osx/
http://osxdaily.com/2015/10/12/secure-empty-trash-equivalent-mac-os-x/

**Comment by drduh** [comment]
I'll add the relevant information from those in a little while. Thanks!
