### ISSUE TITLE
Send diagnostic to Apple and Third Parties, a risk?

### ISSUE THREAD

**Issue by TraderStf** [drduh/OS-X-Security-and-Privacy-Guide#51]
Is there any risk by allowing these options in Syst. Prefs - Security - Confidential: ~
o send diagnostic data to Apple
o share with third party app developers

What's your opinion?
Data are sent, some might be giving a lot of details, are they even encrypted?

**Comment by christopheranderton** [comment]
@TraderStf I always turn this **off** (if you turn it off, if already activated, you need to reboot your computer). It sends different logs back to Apple (crash logs and so on) with SSL. 

However, there is discussions on Apple Forums that this wont stop even if turned off. But it seems the reports is regarding older OS X versions. I have not seen it or encountered this behaviour in OS X 10.11 (15A284) or in Yosemite (as far as i know). 

There is a excellent write up about this topic at https://github.com/fix-macosx/fix-macosx/wiki/Diagnostics-&-Usage-Data 

But my opinion is to turn this off completely, as more active processes running = less security (even if my concern is about privacy in this case, even if most logs sent is nothing to be worried about, there is a added risk). If you encounter a bug or crash that you want to report to Apple or a 3rd party. Just send the crashlog manually (creating a ticket on a bugtracker or a submission on Apple Bug Reporter on the web). That way you can have more control what's being sent to some extent. 

But i'm sure there are others that has more knowledge about this than me (not really my area).

**Comment by TraderStf** [comment]
@christopheranderton thanks for your comments.
For me this kind of 'reports' contain too much information to let it go you-dont-know-where/and-how.
name, directories, apps, ip... what else... george clooney or...

But it does not seems this subject interests others.
