### ISSUE TITLE
Add section about hardening SSH access?

### ISSUE THREAD

**Issue by dnwe** [drduh/OS-X-Security-and-Privacy-Guide#52]
Obviously no-SSHd running is the most secure option, but as it is a typical service that people might run for secure access, particularly in the non-laptop case, then recommending some hardening options might be sensible:

```sh
sudo tee /etc/sshd_config <<EOF
PasswordAuthentication no
ChallengeResponseAuthentication no
UsePAM no
EOF
```

The options are taken from travis-ci's osx slave config. Essentially these would only permit ssh login using public key authentication against an entry in the given $USER's authorized_keys file, all other forms of password-based auth are disabled. If the suggestion in #9 gets added, then you probably also want to add the 'Administrator' username to `DenyUsers` in sshd_config as well. Running `brew install fail2ban` could be a recommended hardening step as well.

There are probably further restrictions that could be added, such as choosing a random [unassigned port](https://www.iana.org/assignments/service-names-port-numbers/service-names-port-numbers.xhtml?search=Unassigned) to open for SSHd access via the ``Port xxxx`` directive in sshd_config. Similarly, enforcing only the most secure ciphers are used via the ``Ciphers`` and ``MACs`` options.

**Comment by drduh** [comment]
Hey @dnwe thanks for the tip. I'll add some ssh/sshd hardening steps soon.
