### ISSUE TITLE
Elaborate on secure backup strategy?

### ISSUE THREAD

**Issue by dnwe** [drduh/OS-X-Security-and-Privacy-Guide#53]
Is it worth elaborating slightly on secure backup strategies and recommend some ways of performing zero-knowledge off-site backups where only you have access to the encryption key used?

https://www.arqbackup.com/
https://spideroak.com/

**Comment by drduh** [comment]
I haven't used either of those products; my encryption strategy is just to use `gpg`. I'll happily outline the steps I use, and/or feel free to PR your methodology. Thanks!

**Comment by rawtaz** [comment]
These backup solutions, is any of them open source? If not, I'm not sure how they can be trusted. They can talk all they want about how the data is encrypted client-side and without their knowledge, but unless the source is available noone can ever verify that easily.

Check out https://restic.github.io/ for a good looking alternative.

Regards, Leo


19 okt 2015 kl. 15:40 skrev Dominic Evans <notifications@github.com>:
