### ISSUE TITLE
Certificate pinning addon (Firefox only)

### ISSUE THREAD

**Issue by dnwe** [drduh/OS-X-Security-and-Privacy-Guide#54]
Unfortunately its currently Firefox-only as Chrome hasn't supplied the necessary hooks yet, but it is still probably worth linking to [Certificate Patrol](http://patrol.psyced.org/).

**Comment by drduh** [comment]
That's a nice suggestion. Feel free to PR (and create a Firefox subsection, if you think it's appropriate) or wait and I'll add it myself.
