### ISSUE TITLE
Can we maintain a list of hashes for OS X disk images?

### ISSUE THREAD

**Issue by sg-s** [drduh/OS-X-Security-and-Privacy-Guide#55]
A problem with downloading OS disk images (as opposed to receiving them on mass-produced physical media like CDs) is the threat that you receive a "special" version that is somehow compromised. 

The threat model here is both Apple trying to slip you with a special version of OS X if it wants to spy on you, or a third party messing with your copy. 

While there is no way for us to know the "true copy", it might be useful to include a hash of a disk image of OS X that we believe to be un-tampered. This way, if you come across a disk image with a different hash, you know something is fishy.

**Comment by drduh** [comment]
Are you asking for a crypto hash for the OS X installer app? Because the one for `InstallESD.dmg (Build 15A284)`, which is used to create an `asr`-able image, is already listed in the guide. Thanks for your comment.

**Comment by sg-s** [comment]
pff ...reading fail. thanks!
