### ISSUE TITLE
Safest settings in miscellaneous Apps

### ISSUE THREAD

**Issue by TraderStf** [drduh/OS-X-Security-and-Privacy-Guide#57]
Don't know if you like this kind of explanations, some are already the main document.
Perhaps a small brief summary, something like

<b>Firefox</b>
OFF - Download abcde
ON - Stop this

Here is one I was not aware of:
http://www.makeuseof.com/tag/google-is-secretly-recording-you-heres-how-to-make-them-stop/

**Comment by drduh** [comment]
Sorry, what do you mean by the Firefox idea? The linked article has nothing really to do with OS X.

**Comment by TraderStf** [comment]
How to set the options in apps, here an example with FF, to be the most secure.

**Comment by drduh** [comment]
Feel free to PR me what you have in mind and I'll take a look. More details about browsers is welcome.
