### ISSUE TITLE
Additional Settings To Add 

### ISSUE THREAD

**Issue by zsn1s** [drduh/OS-X-Security-and-Privacy-Guide#60]
Great work keep it up! Everyone that is helping to add more info thank you.

some other stuff more privacy related

Settings

1. General - Disable "allow handoff between this Mac and your iCoud Devices"
2. Energy Saver - Disable Wake for Wi-Fi network Access
                           - Disable Enable Power nap while plugged into a power adapter
3. Bluetooth - Advanced - Untick all options
4. Sharing - Change Computer Name to something less identifiable
5. Extensions - Disable Unused/Unwanted extensions 

Other:
Encourage using non-admin account (even though this might work for some use scenarios) 

Other goods Apps to check out/recommend:
Espionage by TAO EFFECT - the folder automaton operations make this very powerful tool

**Comment by zsn1s** [comment]
We need to get the services section back that had good advise on services to disable!

**Comment by zsn1s** [comment]
You don't need to add the "recovery partition" for FDE to work... It works just fine without it.

**Comment by drduh** [comment]
Thanks for your suggestions, I will implement them soon.

I agree the services section ought to be brought back, but I noticed that on 10.11, even unloading a few causes other services to go nuts and chew CPU. I would like to put together a graph of what each one does, how they relate to each other, which can be safely unloaded, etc. but it's a time consuming and onerous task I just haven't had time for.

Are you sure about the recovery partition not being required? After all, what does the OS boot into to bring up the Filevault prompt? Maybe you can run `diskutil list` on your Mac and let me know what you see.
