### ISSUE TITLE
Hash for 10.11.1 installer

### ISSUE THREAD

**Issue by rawtaz** [drduh/OS-X-Security-and-Privacy-Guide#61]
Hi,

Can someone verify these hashes for the InstallESD.dmg file are what I have here for the 10.11.1 installer I downloaded from the Mac App Store yesterday? The guide needs to be updated with the new ones.

~~~
InstallESD.dmg

SHA-256: 6275929722c35674fce90d2272d383d49696096e8626ee7f7900dd0334167a9a
SHA-1: 306a080c07e293b6765ba950bab213572704acec
~~~

Also, what's the new build number? That info needs changing too I guess.

Cheers.

**Comment by rawtaz** [comment]
Someone else has the same hash over at http://forums.mydigitallife.info/threads/45579-OSX-full-installer-hash/page3 so at least it's not just me :-)

**Comment by drduh** [comment]
Those are the same sums I see for 10.11.1 installer. Feel free to send a PR or I'll update the document myself later. Looks like it's build `15B41a`.
