### ISSUE TITLE
Request: Disable Bonjour Multicast 10.11

### ISSUE THREAD

**Issue by wizard789** [drduh/OS-X-Security-and-Privacy-Guide#63]
Can I ask if it i possible for someone to provide friendly instructions on how to disable the bonjour multicast in OSX El Capitan 10.11 ? (btw discoveryd is out and mDNSrespoder... is back)

**Comment by drduh** [comment]
I'm not aware of a way to do this without disabling System Integrity Protection in OS X 10.11. Eventually, I'd like to add to the SIP section instructions for modifying settings like these, which are otherwise locked down.

**Comment by drduh** [comment]
I think booting into Recovery Mode, unlocking the encrypted disk, then directly modifying the mDNSResponder plist (optionally, also making any other changes otherwise not possible due to SIP) is the right solution in this instance. I'll leave this issue open for comments before suggesting this in the guide.

**Comment by wizard987** [comment]
thanks for leaving the ticket open hopefully someone will chime in

**Comment by rawtaz** [comment]
@wizard789 I'm curious, what are the issues/risks you see/consider with Bonjour/mDNS[Responder]? I think it's a bit annoying to have this listening and communicating everywhere, but honestly, it's one of the things in OS X that provide a lot of value in terms of ease of use. But I'm genuinely interested in your reasoning!

**Comment by TraderStf** [comment]
Perhaps for something like this
http://thehackernews.com/2015/10/radio-wave-phone-hack.html

**Comment by wizard987** [comment]
Bonjour advertises a lot of information about your system and the services it is running to the local network and according to Apple could allow for remote attackers to access your system. The advice, from Apple is clear - "unless you can trust all the services on your local network, do not use Bonjour" [p.195 OSX Security Configuration Guide]. 

We need to have instructions on how to disable bonjour advertising for el capitan in the instruction set for when users are connecting to untrusted networks.

**Comment by drduh** [comment]
I am going with what @rawtaz said - unless someone can provide evidence of a problem with leaving multicast enabled, going around SIP to turn the feature off seems like a hassle.

**Comment by rawtaz** [comment]
This thing is easily blocked using Little Snitch or simiar anyway :)                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        Från: drduhSkickat: fredagen den 13:e november 2015 20:26Till: drduh/OS-X-Security-and-Privacy-GuideSvara till: drduh/OS-X-Security-and-Privacy-GuideKopia: rawtazÄmne: Re: [OS-X-Security-and-Privacy-Guide] Request: Disable Bonjour Multicast 10.11 (#63)I am going with what @rawtaz said - unless someone can provide evidence of a problem with leaving multicast enabled, going around SIP to turn the feature off seems like a hassle.

—Reply to this email directly or view it on GitHub.

**Comment by GitTheHellOutaHere** [comment]
That doesn't stop it from needlessly sucking RAM, currently 53+ MB on my system.
