### ISSUE TITLE
qrator bot using netbios

### ISSUE THREAD

**Issue by TraderStf** [drduh/OS-X-Security-and-Privacy-Guide#64]
Hello,

littlesnitch just block a netbios outgoing link while I was modifying the firewall.

action: deny
direction: outgoing
process: /usr/sbin/netbiosd
owner: system
destination: 185.94.111.1
port: 56198
protocol: 17

IP from qRator, Russia which collects lot of network data and provides interesting results.

Are the weaknesses of your ISP or Web Hosting Services could have a direct impact?

Thanks,

185.94.108.0 - 185.94.111.255
netname:        RU-QRATOR-20150331
% Information related to '185.94.111.0/24AS197068'

route:          185.94.111.0/24
descr:          radar.qrator.net scan network

**Comment by TraderStf** [comment]
https://radar.qrator.net/faq

**Comment by drduh** [comment]
Is your Mac not behind a NAT (e.g., a home router)? If so, netbiosd shouldn't be talking to machines on the Internet. Do you have some sharing services turned on?

**Comment by TraderStf** [comment]
Hi Doc!
I was testing various things, the router was set in bridge for few hours.
Littlesnitch stops it.
After that I saw that netbios has also 'call' one of my vpn provider few months ago.

Seems qrator archives all security problems. amazing how many... even a free dns like censurfridns.dk seems to have leak... don't mention my ISP.

Thanks for your time.

**Comment by drduh** [comment]
netbios is one of the services I would recommend disabling altogether, if one has no need for it, with `sudo launchctl unload -w /System/Library/LaunchDaemons/com.apple.netbiosd.plist`. I'm just not yet sure how to format and present a list of services to disable in the guide yet, as there's no "one size fits all".

**Comment by drduh** [comment]
Looks like @cirrusj has started annotating a list of 10.10 launch daemons over at http://cirrusj.github.io/Yosemite-Stop-Launch/ which I will try to merge into https://github.com/drduh/OS-X-Security-and-Privacy-Guide/blob/master/14F27_launchd.csv. These lists should give some greater insight into which programs can be disabled or not.
