### ISSUE TITLE
Firewall and signed software

### ISSUE THREAD

**Issue by rawtaz** [drduh/OS-X-Security-and-Privacy-Guide#66]
Hi,

In the advanced settings of the firewall in OS X, there's a checkbox named "Automatically allow signed software to receive incoming connections". This checkbox is enabled by default on a new install of 10.11.1.

While one should be in control of what software is running and listens on ports, perhaps we should encourage setting this to off? Just because a software is signed doesn't mean we want incoming connections to it to be allowed by default.

**Comment by drduh** [comment]
That's a good question. I personally don't have much confidence in the built-in firewall, especially as it only blocks incoming connections and a typical Mac won't have any listening services anyway, but still it's worth investigating. Let me look more into this and update the guide accordingly. Thanks for raising this issue.

**Comment by drduh** [comment]
The guide already recommends turning this off:

>     sudo defaults write /Library/Preferences/com.apple.alf allowsignedenabled -bool false

But I did not do a good job of explaining it.
