### ISSUE TITLE
Killer Software

### ISSUE THREAD

**Issue by wizard987** [drduh/OS-X-Security-and-Privacy-Guide#69]
Consider using this awesome writeup to support dev's that write killer apps for osx

My vote is to add Espionage by TAO EFFECT. This is a great app it uses scrypt instead of keychain plus code is available for review.

What makes this app special it lets you put all your apps and associated data in individual encrypted containers so you can compartmentalize everything on your mac... 

I am worried that software like this is not getting the support it deserves and they will stop development so it's nice to bring some attention to it from this guide

**Comment by drduh** [comment]
I'm not familiar with the software, but I did add mention of it to the [Backup section](https://github.com/drduh/OS-X-Security-and-Privacy-Guide#backup). Let me know if you have more information to add. Thanks!
