### ISSUE TITLE
dnsmasq config for directing only *required* dns lookups to vpn/company's dns server

### ISSUE THREAD

**Issue by dnwe** [drduh/OS-X-Security-and-Privacy-Guide#71]
I know that you already have a comment warning people that "VPN software [typically] overrides DNS settings on connect". However, I wonder if we can do better than that? By adding a pf rule to redirect all udp 53 traffic to the local dnsmasq (to prevent the network config nameserver setting having any effect) and only permit dnscrypt to perform the outgoing lookups (either trivially, using a non-53 port for the public server, or with a more advanced pf rule). Then we can add a small entry under the DNS section to explain how people may add additional server entries to their dnsmasq config to direct DNS queries for certain domains to specific upstream nameservers and hence only use the companies nameserver for looking up private domains within the company, and not sending all their DNS traffic that way.

e.g., `server=/internal.example.com/192.168.100.1` will direct all queries in the internal domain to the correct nameserver. You can specify more than one domain in each server option. If there is more than one internal domain, you just include as many server options as is needed to specify them all.

**Comment by drduh** [comment]
Hey Dominic -

Sorry to keep this issue open for so long. Your suggestion is worthwhile and good, however can be bothersome when connecting to captive portal networks which sometimes work by hijacking DNS to redirect to the portal server. Now, the `pf` rule to redirect traffic should not be necessary, provided one has set the DNS servers to localhost already. I travel frequently and find myself having to accept the DHCP-provided DNS server just to authenticate to the captive portal, before setting it back to localhost in tandem with dnscrypt. I do wonder if I could do better in this regard, and how the guide could be improved. At this moment, I don't have any specific suggestions, though.

**Comment by drduh** [comment]
I'm struggling to come up with ideas to address the problem you've described. I don't think there is a good, feasible way to do it at this time - at least not for most guide readers with limited experience futzing around with network setting nuances. If you can think of a good suggestion to make in the guide, even if it's with a "warning: experts only" disclaimer, I'll be happy to review a pull request. Closing this ticket for now.
