### ISSUE TITLE
increase dnsmasq cache size and disable resolv.conf lookup

### ISSUE THREAD

**Issue by dnwe** [drduh/OS-X-Security-and-Privacy-Guide#73]
not related to security as such, but if people are running the dnsmasq.conf from this guide as-is, it might make sense to include `cache-size` for tuning local caching of replies

```sh
# Set the size of the dnsmasq cache. The default is to keep 150 hostnames
cache-size=8192
```

similarly, as we *only* want to perform lookups via the config's `server=` directives we should explicitly disable use of the resolv.conf for determining available nameservers

```sh
# forces dnsmasq to queries strictly  in  the  order  they   appear
strict-order

# prevent dnsmasq from reading /etc/resolv.conf or any other file
no-resolv
```

**Comment by drduh** [comment]
Do you think both `strict-order` and `no-resolv` are necessary, or just the latter? The man page indicates

> strict-order
> Setting this flag forces dnsmasq to try each query with each server strictly in the order they appear in /etc/resolv.conf

> no-resolv
> Don't read /etc/resolv.conf.

**Comment by dnwe** [comment]
Yeah without looking at the code it wasn't obvious from the man page whether the order of `server=` directives in the conf file was only significant if strict was set

**Comment by dnwe** [comment]
I believe `strict-order` does effect the order in which queries are attempted even for a purely dnsmasq.conf setup as soon as you have more than one `server=` line. I *think* without that directive it will initially just query a random one from the list, and if it can obtain a result from there it will use that server by default next time. A fairly non-deterministic behaviour. However, if you enable strict-order it will always try them in top-down fashion regardless of which happened to respond successfully on previous attempts.

Obviously it has no effect if you only have a single server= entry, so feel free to omit it

**Comment by dnwe** [comment]
@drduh out of interest, why did you drop the `no-resolv` for 432d765?

**Comment by drduh** [comment]
Did I misunderstand you? I thought `no-resolv` isn't necessary. Please send me a PR if I made a mistake.
