### ISSUE TITLE
Path to dnscrypt-resolvers.csv changes when the version number increments.

### ISSUE THREAD

**Issue by victorso** [drduh/OS-X-Security-and-Privacy-Guide#77]
The last dnscrypt upgrade through homebrew changed the path to the `dnscrypt-resolvers.csv` file from `/usr/local/Cellar/dnscrypt-proxy/1.6.0/share/dnscrypt-proxy/dnscrypt-resolvers.csv` to `/usr/local/Cellar/dnscrypt-proxy/1.6.0_1/share/dnscrypt-proxy/dnscrypt-resolvers.csv` 
Is there any way to automatically correct those changes, so it doesn't break the `homebrew.mxcl.dnscrypt-proxy.plist` on each upgrade?

**Comment by bhicks** [comment]
I experienced the same issue, and fixed it by changing the `--resolver-name` line in `/Library/LaunchDaemons/homebrew.mxcl.dnscrypt-proxy.plist` to `<string>--resolvers-list=/usr/local/share/dnscrypt-proxy/dnscrypt-resolvers.csv</string>`.

`/usr/local/share/dnscrypt` should be symlinked to `/usr/local/Cellar/dnscrypt-proxy/1.6.0_3/share/dnscrypt-proxy`, or whatever the current version is.
