### ISSUE TITLE
Same issue like here dnsmasq doesn't resolve 127.0.0.1 #67

### ISSUE THREAD

**Issue by jonaslierschied** [drduh/OS-X-Security-and-Privacy-Guide#80]
Hi drduh, hi rishadafc,

I do have the same problem like rishadafc, but I have not found an solution yet.

If I run "defaults read /Library/LaunchDaemons/homebrew.mxcl.dnsmasq.plist" the following appears
{
KeepAlive = 1;
Label = "homebrew.mxcl.dnsmasq";
ProgramArguments = (
"/usr/local/opt/dnsmasq/sbin/dnsmasq",
"--keep-in-foreground",
"-C",
"/usr/local/etc/dnsmasq.conf"
);
RunAtLoad = 1;
}

If I run "sudo /usr/local/opt/dnsmasq/sbin/dnsmasq --keep-in-foreground -C /usr/local/etc/dnsmasq.conf" the following appears
dnsmasq: failed to create listening socket for 127.0.0.1: Address already in use

Do you know a solution for my problem? Thanks a lot and best regards, Jonas

**Comment by drduh** [comment]
Hey Jonas,

The error means there is already a program running on that port. Can you see it with, `sudo lsof -Pni | grep 53` (or the port you have defined in `dnsmasq.conf`)?

Try killing it with, `sudo pkill <process name>` or `sudo kill <process id>`, or if launchd restarts the process, you can try, `sudo launchctl unload -w /Library/LaunchDaemons/*dnsmasq*.plist` and try starting the program manually as before.

**Comment by drduh** [comment]
I will close this out, but let me know if you have still have trouble.
