### ISSUE TITLE
chrome webrtc leak your real IP

### ISSUE THREAD

**Issue by TraderStf** [drduh/OS-X-Security-and-Privacy-Guide#85]
With Chrome (48+) even behind a VPN, your real IP is leaked.

https://github.com/rentamob/WebRTC-Leak-Prevent
with this extension, the leak is 'closed'.
don't forget to activate its private mode authorization or the leak will be there!

https://whoer.net/
https://diafygi.github.io/webrtc-ips/
to verify if your real IP is leaked

**Comment by TraderStf** [comment]
Chrome config can be edited manually too:
https://support.zenmate.com/hc/en-us/articles/201259661-How-can-I-protect-myself-from-IP-leaks-caused-by-Flash-or-WebRTC-#Chrome_FP

The extension above, also for Firefox.

**Comment by TraderStf** [comment]
https://whoer.net/blog/article/how-to-disable-webrtc-in-various-browsers/

**Comment by drduh** [comment]
I'm still looking through WebRTC blocking extensions and other solutions for Chrome. I was using uBlock Origin, but I'm not certain it still does the job with Chrome 48+. See https://github.com/gorhill/uBlock/wiki/Prevent-WebRTC-from-leaking-local-IP-address

For now, I can't recommend using Chrome if leaking private IP information is of importance. You are probably better off with Tor Browser or hardened Firefox, though they each have their own respective disadvantages as well.

**Comment by TraderStf** [comment]
https://github.com/rentamob/WebRTC-Leak-Prevent
this works, tested on several sites and vpn, for chrome, not tested for FF.

Must check this, not sure
one solution use an 'intermediate' server, so the leak always shows this one
which means for privacy you are going through that server

the other is that you can do manually, my 2nd post, I think it is just turn webrtc off.

**Comment by TraderStf** [comment]
A bit stupid but IP6 must be enabled 'everywhere'...
mine was not in my routeur when I made the first tests... so everything seems ok... hopefully I remember the router add IP6 off.
