### ISSUE TITLE
Add usbkill to physical security list?

### ISSUE THREAD

**Issue by vsaw** [drduh/OS-X-Security-and-Privacy-Guide#86]
> « usbkill » is an anti-forensic kill-switch that waits for a change on your USB ports and then immediately shuts down your computer.

It especially mentions OS X support which, although I never tested it. See https://github.com/hephaest0s/usbkill

**Comment by drduh** [comment]
That looks intriguing. Why don't you add it to the Physical Access section, or I can do it.

**Comment by vsaw** [comment]
Done, I just wasn't sure if anyone found it suitable or interesting.
