### ISSUE TITLE
Apple can read your imessages, are encrypted with Apple's key!

### ISSUE THREAD

**Issue by TraderStf** [drduh/OS-X-Security-and-Privacy-Guide#88]
FYI !
Incredible...
http://www.scmagazine.com/apple-can-read-your-imessages-despite-them-being-encrypted/article/467675

**Comment by drduh** [comment]
This doesn't surprise me. End to end encryption only works when your adversary doesn't control PKI, which is what Apple does with iMessage. And anyway, it's a closed source application running on a closed source operating system, which leaves a lot to be desired. If you think it's necessary and have an idea about how to call out iMessage in the guide, send a PR, please.
