### ISSUE TITLE
Suggestion Objective-See OSX Lockdown tool

### ISSUE THREAD

**Issue by RaDeleon** [drduh/OS-X-Security-and-Privacy-Guide#96]
A new tool out from the same people who made blockblock and knockknock. It basically does what about 32 commands in terminal would do and in 10seconds or less. I think it should be in the guide as part of the guide in order to help some of the newer users secure there macs.

https://objective-see.com/products/lockdown.html

**Comment by drduh** [comment]
This is a reasonable suggestion. Would you care to submit a pull request with your recommendation in an appropriate place? Thanks!

**Comment by RaDeleon** [comment]
Yes I will do that tonight

**Comment by TraderStf** [comment]
Some will complain that Patrick is former NSA...
I am using all his apps and I am still alive. just kidding. hee really, yep.
https://github.com/drduh/OS-X-Security-and-Privacy-Guide/issues/11

**Comment by drduh** [comment]
A footnote to Issue #90 in which the concern is discussed is worthwhile, for sure.

**Comment by RaDeleon** [comment]
Ive seen all his talks and he states he doesnt include the source be AV companies arent doing there jobs right and are lazy and he doesnt want them basically copying his code and selling it or anyone else. I haven't read the post yet I will do that now.

**Comment by TraderStf** [comment]
@drduh If you allow me, @PatrickWardle does not deserve this footnote.
He's doing a great job for free.
He just releases a new tool, RansomWhere to detect and stop unusual encryption activities.
I have made a small donations few months ago, compared to all the tools provided that's nothing.
All are very good, not a single problem.
