### ISSUE TITLE
FYI - Ransomware in Transmission app!

### ISSUE THREAD

**Issue by TraderStf** [drduh/OS-X-Security-and-Privacy-Guide#97]
Ransomware developers target Apple users. Transmission download ~this week-end contains KeRanger ransomware, 400USD. http://www.csoonline.com/article/3041080/security/ransomware-developers-target-apple-customers.html

http://researchcenter.paloaltonetworks.com/2016/03/new-os-x-ransomware-keranger-infected-transmission-bittorrent-client-installer/

**Comment by drduh** [comment]
Fixed in https://github.com/drduh/OS-X-Security-and-Privacy-Guide/commit/495e27c52dd17610430dba7407fbb54cebd4505f
