### ISSUE TITLE
I2P anonymous overlay network

### ISSUE THREAD

**Issue by TraderStf** [drduh/OS-X-Security-and-Privacy-Guide#98]
I2P is an anonymous overlay network - a network within a network. It is intended to protect communication from dragnet surveillance and monitoring by third parties such as ISPs.

https://geti2p.net/en/

https://github.com/i2p/i2p.i2p

**Comment by drduh** [comment]
I don't know much about I2P, so I'm not sure whether I can make a recommendation for/against its use. Is anyone more familiar with this software?

**Comment by filipecatraia** [comment]
I remember trying at some point, and failing to get it up (I give up on things easily when pressed for time/patience).

**Comment by drduh** [comment]
Unless anyone can vouch for the integrity and security of this anonymous network software, which I still haven't had an opportunity to thoroughly use and evaluate, I think recommending Tor and perhaps I2P as a footnote only makes most sense.
