### ISSUE TITLE
SSL/TLS and SHA-2 as minimum requirements

### ISSUE THREAD

**Issue by TraderStf** [drduh/OS-X-Security-and-Privacy-Guide#99]
https://www.symantec-wss.com/campaigns/17028/assets/symantec-top-five-ssl-ch.pdf

Download now and discover why:
SSL/TLS certificates need to be at least 2048-bit RSA or 256-bit ECC
The only secure, standard hash algorithm is SHA-2
Root certificates must be heavily defended by the CA
The security of systems storing and using private SSL/TLS keys must also be tightly guarded

**Comment by TraderStf** [comment]
http://www.computerworld.com/article/3014591/security/google-to-revoke-trust-in-a-symantec-root-certificate.html

**Comment by drduh** [comment]
This advice is good, but not really specific to Mac. I think anyone determined to find out best practices for TLS can do so easily elsewhere.
